#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:


language: python

python:
  - 3.6
  - 2.7

env:
  - DJANGO=1.11.1

install:
  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test --noinput